INSERT INTO region (region_code) VALUES
     ('ASIA'),
     ('AMERICAS'),
     ('CHINA'),
     ('EUROPE');

INSERT INTO country (country_code, region_code) VALUES
    ('BN', 'ASIA'),
    ('SG', 'ASIA'),
    ('AZ', 'ASIA'),
    ('ID', 'ASIA'),
    ('JP', 'ASIA'),
    ('TR', 'EUROPE'),
    ('HK', 'ASIA'),
    ('US', 'AMERICAS'),
    ('CA', 'AMERICAS'),
    ('AU', 'AMERICAS'),
    ('BR', 'AMERICAS'),
    ('NL', 'EUROPE'),
    ('NO', 'EUROPE'),
    ('DK', 'EUROPE'),
    ('DE', 'EUROPE'),
    ('SE', 'EUROPE'),
    ('CH', 'EUROPE'),
    ('ES', 'EUROPE'),
    ('GB', 'EUROPE'),
    ('AT', 'EUROPE'),
    ('IT', 'EUROPE'),
    ('CZ', 'EUROPE'),
    ('PT', 'EUROPE'),
    ('FR', 'EUROPE'),
    ('FI', 'EUROPE'),
    ('CN', 'CHINA'),
    ('TW', 'CHINA');